# ==========================================
# G U I A   D E   E J E C U C I O N
# ==========================================
# Comando de ejecucion para MacOS / Linux (ejecutar DENTRO de la carpeta frontend):
# docker run --rm -v "$PWD:/usr/src" -e SONAR_HOST_URL="http://host.docker.internal:9000" sonarsource/sonar-scanner-cli
#
# Comando de ejecucion para Windows (CMD) (ejecutar DENTRO de la carpeta frontend):
# docker run --rm -v "%cd%:/usr/src" -e SONAR_HOST_URL="http://host.docker.internal:9000" sonarsource/sonar-scanner-cli
#
# Comando de ejecucion para Windows (PowerShell) (ejecutar DENTRO de la carpeta frontend):
# docker run --rm -v "${PWD}:/usr/src" -e SONAR_HOST_URL="http://host.docker.internal:9000" sonarsource/sonar-scanner-cli
# ==========================================

sonar.projectKey=dysto-ai-frontend
sonar.projectName=dysto-ai-frontend

sonar.login=sqp_058a9fd7862c06314d6a548a00d52f79c3cf6669

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,.next/**,public/**,**/*.md,package*.json,sonar-project.properties

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.javascript.node.maxspace=8192
